{{- if and (not .Values.server.existingSecret) .Values.server.token -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "esphome-fleet-worker.fullname" . }}
  labels:
    {{- include "esphome-fleet-worker.labels" . | nindent 4 }}
type: Opaque
stringData:
  SERVER_TOKEN: {{ .Values.server.token | quote }}
{{- end -}}
